(function() {
    'use strict';

    define([
        'angular',
        'home',
        'about'
    ], function() {
        var app = angular.module('app', [
            'app.home',
            'about',
            'ngNewRouter'
        ]);

        var appConfigInjectables = ['$compileProvider', '$componentLoaderProvider'];
        function appConfig($compileProvider, $componentLoaderProvider) {
            // Disable ng-scope and other debug code generated by angular. Comment this line if you wish to debug the application.
            $compileProvider.debugInfoEnabled(false);
            console.log('$componentLoaderProvider', $componentLoaderProvider);

            function setControllerName(something) {
                console.log('something', something);
                this.name = something + 'Controller';
            }
            //$componentLoaderProvider.setCtrlNameMapping(setControllerName);
        }

        app.config(appConfigInjectables.concat([appConfig]));

        var appControllerInjectables = ['$router', '$componentLoader'];
        function appController($router, $componentLoaderProvider) {
            console.log('$componentLoaderProvider', $componentLoaderProvider);
            $router.config([
                { path: '/', redirectTo: 'home' },
                { path: '/home', component: 'home' },
                { path: '/about', component: 'about' }
            ]);
        }

        app.controller('appController', appControllerInjectables.concat([appController]));

        return angular.bootstrap(document, ['app']); // Manually bootstrap angular, on Dom ready
    });
})();