(function(angular) {
    'use strict';

    define([
        'angular'
    ], function() {
        // Module declaration. App is the main entry point for the entire app.
        angular.module('app', []);
        // Called the app module.
        var app = angular.module('app');

        var appConfigInjectables = ['$compileProvider'];
        function appConfig($compileProvider) {
            // Disable ng-scope and other debug code generated by angular. Comment this line if you wish to debug the application.
            $compileProvider.debugInfoEnabled(false);
        }
        app.config(appConfigInjectables.concat([appConfig]));

        angular.element(document).ready(function() {
            return angular.bootstrap(document, ['app']);
        });
    });
})(angular);
